spring:
  profiles:
    include: key
  datasource: #mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:


  jpa:
    hibernate:
      ddl-auto: validate
      generate-ddl: true
      properties:
        hibernate:
          show_sql: true
          format_sql: true

logging.level:
  org.hibernate.SQL: info

server:
  address:
#  port: 80
