spring:
  datasource: #mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.37.120:3306/rolling_paper?serverTimezone=Asia/Seoul
    username: bong
    password: bong2834


  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          show_sql: true
          format_sql: true

logging.level:
  org.hibernate.SQL: info
