spring:
  messages:
    encoding: UTF-8
    basename: messages,error

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true

logging.level:
  org.hibernate.SQL: debug




---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: dev

